"""Nueva Migración Automática

Revision ID: 0b16d62bfd5f
Revises: bfc4cefcc57f
Create Date: 2025-10-30 20:57:54.121986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b16d62bfd5f'
down_revision: Union[str, Sequence[str], None] = 'bfc4cefcc57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
