"""Crear tabla excel_data

Revision ID: 693808f216a0
Revises: 
Create Date: 2025-08-31 16:03:34.451921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '693808f216a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_data_file_id'), 'excel_data', ['file_id'], unique=False)
    op.drop_index(op.f('ix_incidences_id'), table_name='incidences')
    op.drop_index(op.f('ix_incidences_number'), table_name='incidences')
    op.drop_table('incidences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidences',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('inicio_de_falla', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_de_envio', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_resolucion_falla', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_assignment_group', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('resolution_code_n1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('resolution_code_n2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('resolution_code_n3', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('resolution_notes', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('afectacion_al_servicio', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('category_ci', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cmdb_ci', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_incidences_number'), 'incidences', ['number'], unique=True)
    op.create_index(op.f('ix_incidences_id'), 'incidences', ['id'], unique=False)
    op.drop_index(op.f('ix_excel_data_file_id'), table_name='excel_data')
    op.drop_table('excel_data')
    # ### end Alembic commands ###
