"""Nueva Migración Automática

Revision ID: 7d0ac0d368f1
Revises: 06ade8754c65
Create Date: 2026-01-17 15:53:18.351045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d0ac0d368f1'
down_revision: Union[str, Sequence[str], None] = '06ade8754c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_panda', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_de_red', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coordinador', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ingeniero', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('km', sa.Float(), nullable=True),
    sa.Column('ingenieria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kmz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_site_code'), 'regions', ['site_code'], unique=False)
    op.drop_table('tareas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id_tarea', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('grupo_de_asignacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('plataforma', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nombre_de_tarea', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('prioridad', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('incidente', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_de_creacion', mysql.DATETIME(), nullable=True),
    sa.Column('fin_de_semana', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('viernes_fuera_de_horario_laboral', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mes', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('semana', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('trimestre', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tipo_de_solicitud', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('motivo_del_estado', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_solicitud_almacen', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_liberacion_almacen', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_entrega_en_sitio', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_solicitud_a_proveedor', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_de_envio_del_proveedor', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_entrega_en_sitio_spms', mysql.DATETIME(), nullable=True),
    sa.Column('tipo_de_transporte', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('asignado_a', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('motivo_fuera_de_sla', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tiempo_1', mysql.FLOAT(), nullable=True),
    sa.Column('etapa_1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('horas_1', mysql.FLOAT(), nullable=True),
    sa.Column('hrs_1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dias_1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sla_no', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tiempo_2', mysql.FLOAT(), nullable=True),
    sa.Column('etapa_2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('horas_2', mysql.FLOAT(), nullable=True),
    sa.Column('hrs_2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dias_2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sla_almacen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tiempo_3', mysql.FLOAT(), nullable=True),
    sa.Column('etapa_3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('horas_3', mysql.FLOAT(), nullable=True),
    sa.Column('hrs_3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dias_3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sla_trafico', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('es_top_10', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status_calculo', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tarea'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_regions_site_code'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
