"""Nueva Migración Automática

Revision ID: bfc4cefcc57f
Revises: 
Create Date: 2025-10-30 20:57:49.322371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfc4cefcc57f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id_tarea', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grupo_de_asignacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plataforma', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nombre_de_tarea', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prioridad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('incidente', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fin_de_semana', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('viernes_fuera_de_horario_laboral', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semana', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trimestre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_de_solicitud', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motivo_del_estado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_solicitud_almacen', sa.DateTime(), nullable=True),
    sa.Column('fecha_liberacion_almacen', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_en_sitio', sa.DateTime(), nullable=True),
    sa.Column('fecha_solicitud_a_proveedor', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_envio_del_proveedor', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_en_sitio_spms', sa.DateTime(), nullable=True),
    sa.Column('tipo_de_transporte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asignado_a', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motivo_fuera_de_sla', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tiempo_1', sa.Float(), nullable=True),
    sa.Column('etapa_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('horas_1', sa.Float(), nullable=True),
    sa.Column('hrs_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dias_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sla_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tiempo_2', sa.Float(), nullable=True),
    sa.Column('etapa_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('horas_2', sa.Float(), nullable=True),
    sa.Column('hrs_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dias_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sla_almacen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tiempo_3', sa.Float(), nullable=True),
    sa.Column('etapa_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('horas_3', sa.Float(), nullable=True),
    sa.Column('hrs_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dias_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sla_trafico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('es_top_10', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_calculo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id_tarea')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    # ### end Alembic commands ###
